version: "3"
services:
    spring-backend:
        build: twatter-spring/
        container_name: spring-backend
        ports:
            - "8080:8080"
        environment: 
            - TWATTER_POSTGRESQL_DB_PORT=5432
            - TWATTER_POSTGRESQL_DB_NAME=twatter
            - TWATTER_POSTGRESQL_DB_USERNAME=twatter
            - TWATTER_POSTGRESQL_DB_PASSWORD=twattertwatter
        
    react-frontend:
        build: frontend/
        container_name: twatter_frontend
        ports: 
            - "3000:3000"
        stdin_open: true